levels:
  rqt_dotgraph:
    reporting:
      print_to_console:
    tool:
      bandit:
        flags: ""
      black:
        flags: ""
      cccc:
        flags: ""
      docformatter:
        flags: "--wrap-summaries 88 --wrap-descriptions 88"
      lizard:
        flags: ""
      markdownlint:
        flags: ""
      # Set max line length to match black.
      pycodestyle:
        flags: "--max-line-length=88"
      pydocstyle:
        flags: ""
      pyflakes:
        flags: ""
      pylint:
        flags: ""
      xmllint:
        flags: ""
      yamllint:
        flags: "-d '{extends: default,
                     rules: {
                       colons: {max-spaces-before: 0, max-spaces-after: -1},
                       commas: disable,
                       document-start: disable,
                       line-length: disable}}'"
