name: test

on: [pull_request, push] # NOLINT

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
      fail-fast: false
    steps:
      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@0.1.1
        with:
          required-ros-distributions: foxy

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools
          python -m pip install --upgrade wheel
          python -m pip install --upgrade coverage
          python -m pip install --upgrade statick
          python -m pip install --upgrade statick-md
          python -m pip install --upgrade black

      # Have to install newer version from non-apt source due to SSL library compatibility issues.
      - name: Install tools (Linux)
        run: |
          sudo apt install curl
          curl -sL https://deb.nodesource.com/setup_10.x -o nodesource_setup.sh
          sudo bash nodesource_setup.sh
          sudo apt install nodejs
          sudo npm install -g n
          sudo n stable
          sudo npm install -g markdownlint-cli
          rm nodesource_setup.sh

      - name: build and test
        id: built-and-test
        uses: ros-tooling/action-ros-ci@0.1.0
        with:
          package-name: rqt_dotgraph
          target-ros2-distro: foxy
          vcs-repo-file-url: ""
          colcon-mixin-name: coverage-pytest
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml

      - name: Codecov
        uses: codecov/codecov-action@v1.1.0
        with:
          # file: ros_ws/lcov/total_coverage.info
          file: ${{ steps.build-and-test.outputs.ros-workspace-directory-name }}/lcov/total_coverage.info
          flags: unittests
          name: codecov-umbrella
          # yml: ./codecov.yml
          # fail_ci_if_error: false

      - name: Statick Documentation
        run: |
          cd ${{ steps.build-and-test.outputs.ros-workspace-directory-name }}
          statick ./src --ws --check --profile documentation.yaml

      - name: Statick
        run: |
          cd ${{ steps.build-and-test.outputs.ros-workspace-directory-name }}
          mkdir statick-output
          statick ./src/rqt_dotgraph --output-directory statick-output --user-paths ./src/rqt_dotgraph/statick_config --profile rqt_dotgraph.yaml
