name: test

on: # NOLINT
  pull_request:
  push:
  schedule:
    - cron: '0 10 * * MON'
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ros_distribution:
          - iron
          - humble
          - jazzy
          - rolling

        include:
          # Iron Irwini (May 2023 - November 2024)
          - docker_image: osrf/ros:iron-desktop-full
            ros_distribution: iron
            ros_version: 2

          # Humble Hawksbill (May 2022 - May 2027)
          - docker_image: osrf/ros:humble-desktop-full
            ros_distribution: humble
            ros_version: 2

          # Jazzy Jalisco (May 2024 - May 2029)
          - docker_image: osrf/ros:jazzy-desktop-full
            ros_distribution: jazzy
            ros_version: 2

          # Rolling Ridley (No End-Of-Life)
          - docker_image: osrf/ros:rolling-desktop-full
            ros_distribution: rolling
            ros_version: 2

    container:
      image: ${{ matrix.docker_image }}

    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}

      - name: Build and test
        if: ${{ matrix.ros_version == 2 }}
        id: built-and-test
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: rqt_dotgraph
          target-ros2-distro: ${{ matrix.ros_distribution }}
          vcs-repo-file-url: ""
          colcon-defaults: |
            {
              "build": {
                "mixin": ["coverage-pytest"]
              },
              "test": {
                "mixin": ["coverage-pytest"]
              }
            }
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/1ddb69bedfd1f04c2f000e95452f7c24a4d6176b/index.yaml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Setup copy of repo
        uses: actions/checkout@v4

      - name: Install Python dependencies
        run: |
          python -m venv .venv
          . .venv/bin/activate
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools
          python -m pip install --upgrade wheel
          python -m pip install --upgrade coverage
          python -m pip install --upgrade statick
          python -m pip install --upgrade statick-md
          python -m pip install --upgrade pycodestyle
          python -m pip install --upgrade pyflakes

      - name: Install Apt dependencies (Linux)
        run: |
          sudo apt install cccc
          sudo apt install libxml2
          sudo apt install libxml2-utils
          npm install -g markdownlint-cli

      - name: Statick
        run: |
          . .venv/bin/activate
          . /opt/ros/${{ matrix.ros_distribution }}/setup.sh
          statick . --check --output-directory statick-output --user-paths ./statick_config --profile rqt_dotgraph_profile.yaml --config rqt_dotgraph_config.yaml --log info --timings
