name: test

on: [pull_request, push] # NOLINT

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ros_distribution:
          - humble
          - rolling

        include:
          # Humble Hawksbill (May 2022 - May 2027)
          - docker_image: osrf/ros:humble-desktop-full
            ros_distribution: humble
            ros_version: 2

          # Rolling Ridley (No End-Of-Life)
          - docker_image: osrf/ros:rolling-desktop-full
            ros_distribution: rolling
            ros_version: 2

    container:
      image: ${{ matrix.docker_image }}

    steps:
      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@v0.6
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}

      - name: Build and test
        if: ${{ matrix.ros_version == 2 }}
        id: built-and-test
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: rqt_dotgraph
          target-ros2-distro: ${{ matrix.ros_distribution }}
          vcs-repo-file-url: ""
          colcon-defaults: |
            {
              "build": {
                "mixin": ["coverage-pytest"]
              },
              "test": {
                "mixin": ["coverage-pytest"]
              }
            }
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/1ddb69bedfd1f04c2f000e95452f7c24a4d6176b/index.yaml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: false

      - name: Setup copy of repo
        uses: actions/checkout@v3

      - name: Statick
        uses: sscpac/statick-action@v0.9.2
        with:
          check: true
          user_paths: statick_config
          profile: rqt_dotgraph_profile.yaml
          config: rqt_dotgraph_config.yaml
          log_level: info
          timings: true
