name: test

on: [pull_request, push] # NOLINT

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
    steps:
      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@0.1.1
        with:
          required-ros-distributions: foxy

      - name: Install Python dependencies
        run: |
          # This is not the preferred way to install python tools but seems to be required here.
          # "python3 -m pip" would be preferred.
          sudo pip3 install --upgrade pip
          sudo pip3 install --upgrade setuptools
          sudo pip3 install --upgrade wheel
          sudo pip3 install --upgrade coverage
          sudo pip3 install --upgrade statick
          sudo pip3 install --upgrade statick-md
          sudo pip3 install --upgrade black
          sudo pip3 install --upgrade docformatter
          sudo pip3 install --upgrade lizard
          sudo pip3 install --upgrade pycodestyle
          sudo pip3 install --upgrade pydocstyle
          sudo pip3 install --upgrade pyflakes
          sudo pip3 install --upgrade pylint
          sudo pip3 install --upgrade yamllint

      # Have to install newer version from non-apt source due to SSL library compatibility issues.
      - name: Install Apt dependencies (Linux)
        run: |
          sudo apt install cccc
          sudo apt install libxml2
          sudo apt install libxml2-utils
          sudo apt install curl
          curl -sL https://deb.nodesource.com/setup_10.x -o nodesource_setup.sh
          sudo bash nodesource_setup.sh
          sudo apt install nodejs
          sudo npm install -g n
          sudo n stable
          sudo npm install -g markdownlint-cli
          rm nodesource_setup.sh

      - name: build and test
        id: built-and-test
        uses: ros-tooling/action-ros-ci@0.1.0
        with:
          package-name: rqt_dotgraph
          target-ros2-distro: foxy
          vcs-repo-file-url: ""
          colcon-mixin-name: coverage-pytest
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml

      - name: Codecov
        uses: codecov/codecov-action@v1.1.0
        with:
          # file: ros_ws/lcov/total_coverage.info
          # file: ${{ steps.build-and-test.outputs.ros-workspace-directory-name }}/lcov/total_coverage.info
          flags: unittests
          name: codecov-umbrella
          # yml: ./codecov.yml
          # fail_ci_if_error: false

      - name: Setup copy of repo
        uses: actions/checkout@v2

      - name: Statick
        run: |
          source /opt/ros/foxy/setup.sh
          mkdir statick-output
          statick . --check --output-directory statick-output --user-paths ./statick_config --profile rqt_dotgraph_profile.yaml --config rqt_dotgraph_config.yaml
